#!/bin/bash
# shellcheck disable=SC2034

# Inventário de nós
export CP_IP="192.168.30.52"
export WORKERS=("192.168.30.53" "192.168.30.54")
export REMOTE_SSH_USER="${REMOTE_SSH_USER:-utfpr}"
REMOTE_DEFAULT_BASE_DIR="/home/${REMOTE_SSH_USER}/adb-k8s"
export REMOTE_BASE_DIR="${REMOTE_BASE_DIR:-${REMOTE_DEFAULT_BASE_DIR}}"
REMOTE_DEFAULT_CONTROL_PATH="${HOME}/.ssh/adb-%C"
export REMOTE_SSH_CONTROL_PATH="${REMOTE_SSH_CONTROL_PATH:-${REMOTE_DEFAULT_CONTROL_PATH}}"
REMOTE_DEFAULT_SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=${REMOTE_SSH_CONTROL_PATH}"
export REMOTE_SSH_OPTIONS="${REMOTE_SSH_OPTIONS:-${REMOTE_DEFAULT_SSH_OPTIONS}}"

# Networking
export POD_CIDR="10.10.0.0/16"
export SVC_CIDR="10.96.0.0/12"

# MetalLB
export LB_POOL_START="192.168.30.100"
export LB_POOL_END="192.168.30.120"
# Deixe em branco para IP dinâmico; defina para fixar manualmente.
export INGRESS_VIP=""

# Hostnames (opcionais) - sobrescrevem a geração automática baseada no IP do ingress (formato slug: 192-168-30-100)
export RANCHER_HOST_OVERRIDE=""
export GRAFANA_HOST_OVERRIDE=""
export LONGHORN_HOST_OVERRIDE=""
export HUBBLE_HOST_OVERRIDE=""
export ARGOCD_HOST_OVERRIDE=""
export INGRESS_HOST_TEMPLATE="%s.%s.sslip.io"

# TLS
export TLS_ENABLED="${TLS_ENABLED:-0}"
export TLS_CLUSTER_ISSUER="${TLS_CLUSTER_ISSUER:-selfsigned-cluster-issuer}"

# Rancher
export RANCHER_REPLICAS="${RANCHER_REPLICAS:-1}"
export RANCHER_ENABLE_FLEET="${RANCHER_ENABLE_FLEET:-0}"
export RANCHER_ENABLE_TELEMETRY="${RANCHER_ENABLE_TELEMETRY:-0}"
export RANCHER_STARTUP_FAILURE_THRESHOLD="${RANCHER_STARTUP_FAILURE_THRESHOLD:-30}"
export RANCHER_HELM_CHART_OVERRIDE="${RANCHER_HELM_CHART_OVERRIDE:-}"

# Argo CD
export ARGOCD_NAMESPACE="${ARGOCD_NAMESPACE:-argocd}"

# Tenants / vCluster

# tenant configurado em `adb-api-3/k8s/tenants`
export TENANTS="${TENANTS:-abc xyz}"
export TENANT_NAMESPACE_PREFIX="${TENANT_NAMESPACE_PREFIX:-vcluster-}"
export TENANT_TARGET_NAMESPACE="${TENANT_TARGET_NAMESPACE:-app}"
export TENANT_APP_NAMESPACE="${TENANT_APP_NAMESPACE:-${TENANT_TARGET_NAMESPACE}}"
export SHARED_VCLUSTER_NAME="${SHARED_VCLUSTER_NAME:-shared}"
export SHARED_VCLUSTER_NAMESPACE="${SHARED_VCLUSTER_NAMESPACE:-vcluster-shared}"
export ENABLE_SHARED_VCLUSTER="${ENABLE_SHARED_VCLUSTER:-1}"

# Argo CD applications (GitOps)
export ADB_API_PATH_ROOT="${ADB_API_PATH_ROOT:-k8s/tenants}"
export INTERPOLATION_PATH="${INTERPOLATION_PATH:-k8s/overlays/shared}"
export INTERPOLATION_NAMESPACE="${INTERPOLATION_NAMESPACE:-processing}"

# vCluster resource profiles (override apenas se necessário)
export PRIVATE_API_REQUEST_CPU="${PRIVATE_API_REQUEST_CPU:-200m}"
export PRIVATE_API_REQUEST_MEMORY="${PRIVATE_API_REQUEST_MEMORY:-256Mi}"
export PRIVATE_API_LIMIT_CPU="${PRIVATE_API_LIMIT_CPU:-600m}"
export PRIVATE_API_LIMIT_MEMORY="${PRIVATE_API_LIMIT_MEMORY:-512Mi}"
export PRIVATE_CONTROLLER_MANAGER_REQUEST_CPU="${PRIVATE_CONTROLLER_MANAGER_REQUEST_CPU:-150m}"
export PRIVATE_CONTROLLER_MANAGER_REQUEST_MEMORY="${PRIVATE_CONTROLLER_MANAGER_REQUEST_MEMORY:-192Mi}"
export PRIVATE_CONTROLLER_MANAGER_LIMIT_CPU="${PRIVATE_CONTROLLER_MANAGER_LIMIT_CPU:-400m}"
export PRIVATE_CONTROLLER_MANAGER_LIMIT_MEMORY="${PRIVATE_CONTROLLER_MANAGER_LIMIT_MEMORY:-384Mi}"
export PRIVATE_SCHEDULER_REQUEST_CPU="${PRIVATE_SCHEDULER_REQUEST_CPU:-100m}"
export PRIVATE_SCHEDULER_REQUEST_MEMORY="${PRIVATE_SCHEDULER_REQUEST_MEMORY:-128Mi}"
export PRIVATE_SCHEDULER_LIMIT_CPU="${PRIVATE_SCHEDULER_LIMIT_CPU:-300m}"
export PRIVATE_SCHEDULER_LIMIT_MEMORY="${PRIVATE_SCHEDULER_LIMIT_MEMORY:-256Mi}"
export PRIVATE_SYNCER_REQUEST_CPU="${PRIVATE_SYNCER_REQUEST_CPU:-200m}"
export PRIVATE_SYNCER_REQUEST_MEMORY="${PRIVATE_SYNCER_REQUEST_MEMORY:-256Mi}"
export PRIVATE_SYNCER_LIMIT_CPU="${PRIVATE_SYNCER_LIMIT_CPU:-500m}"
export PRIVATE_SYNCER_LIMIT_MEMORY="${PRIVATE_SYNCER_LIMIT_MEMORY:-512Mi}"
export PRIVATE_CONTROL_PLANE_REPLICAS="${PRIVATE_CONTROL_PLANE_REPLICAS:-1}"
export PRIVATE_CONTROL_PLANE_REQUEST_CPU="${PRIVATE_CONTROL_PLANE_REQUEST_CPU:-450m}"
export PRIVATE_CONTROL_PLANE_REQUEST_MEMORY="${PRIVATE_CONTROL_PLANE_REQUEST_MEMORY:-576Mi}"
export PRIVATE_CONTROL_PLANE_LIMIT_CPU="${PRIVATE_CONTROL_PLANE_LIMIT_CPU:-1300m}"
export PRIVATE_CONTROL_PLANE_LIMIT_MEMORY="${PRIVATE_CONTROL_PLANE_LIMIT_MEMORY:-1152Mi}"
export PRIVATE_CONTROL_PLANE_K8S_VERSION="${PRIVATE_CONTROL_PLANE_K8S_VERSION:-}"

export SHARED_API_REQUEST_CPU="${SHARED_API_REQUEST_CPU:-250m}"
export SHARED_API_REQUEST_MEMORY="${SHARED_API_REQUEST_MEMORY:-320Mi}"
export SHARED_API_LIMIT_CPU="${SHARED_API_LIMIT_CPU:-700m}"
export SHARED_API_LIMIT_MEMORY="${SHARED_API_LIMIT_MEMORY:-640Mi}"
export SHARED_CONTROLLER_MANAGER_REQUEST_CPU="${SHARED_CONTROLLER_MANAGER_REQUEST_CPU:-180m}"
export SHARED_CONTROLLER_MANAGER_REQUEST_MEMORY="${SHARED_CONTROLLER_MANAGER_REQUEST_MEMORY:-256Mi}"
export SHARED_CONTROLLER_MANAGER_LIMIT_CPU="${SHARED_CONTROLLER_MANAGER_LIMIT_CPU:-450m}"
export SHARED_CONTROLLER_MANAGER_LIMIT_MEMORY="${SHARED_CONTROLLER_MANAGER_LIMIT_MEMORY:-448Mi}"
export SHARED_SCHEDULER_REQUEST_CPU="${SHARED_SCHEDULER_REQUEST_CPU:-120m}"
export SHARED_SCHEDULER_REQUEST_MEMORY="${SHARED_SCHEDULER_REQUEST_MEMORY:-160Mi}"
export SHARED_SCHEDULER_LIMIT_CPU="${SHARED_SCHEDULER_LIMIT_CPU:-320m}"
export SHARED_SCHEDULER_LIMIT_MEMORY="${SHARED_SCHEDULER_LIMIT_MEMORY:-320Mi}"
export SHARED_SYNCER_REQUEST_CPU="${SHARED_SYNCER_REQUEST_CPU:-220m}"
export SHARED_SYNCER_REQUEST_MEMORY="${SHARED_SYNCER_REQUEST_MEMORY:-256Mi}"
export SHARED_SYNCER_LIMIT_CPU="${SHARED_SYNCER_LIMIT_CPU:-520m}"
export SHARED_SYNCER_LIMIT_MEMORY="${SHARED_SYNCER_LIMIT_MEMORY:-512Mi}"
export SHARED_CONTROL_PLANE_REPLICAS="${SHARED_CONTROL_PLANE_REPLICAS:-1}"
export SHARED_CONTROL_PLANE_REQUEST_CPU="${SHARED_CONTROL_PLANE_REQUEST_CPU:-550m}"
export SHARED_CONTROL_PLANE_REQUEST_MEMORY="${SHARED_CONTROL_PLANE_REQUEST_MEMORY:-736Mi}"
export SHARED_CONTROL_PLANE_LIMIT_CPU="${SHARED_CONTROL_PLANE_LIMIT_CPU:-1470m}"
export SHARED_CONTROL_PLANE_LIMIT_MEMORY="${SHARED_CONTROL_PLANE_LIMIT_MEMORY:-1408Mi}"
export SHARED_CONTROL_PLANE_K8S_VERSION="${SHARED_CONTROL_PLANE_K8S_VERSION:-}"

export VC_TENANT_MANIFEST_ROOT="${VC_TENANT_MANIFEST_ROOT:-${ROOT_DIR}/adb-api-3/k8s/tenants}"
export VC_INTERPOLATION_OVERLAY_DIR="${VC_INTERPOLATION_OVERLAY_DIR:-${ROOT_DIR}/adb-interpolation-api/k8s/overlays/shared}"
export VCLUSTER_SERVICE_TYPE="${VCLUSTER_SERVICE_TYPE:-LoadBalancer}"
export VCLUSTER_METALLB_POOL="${VCLUSTER_METALLB_POOL:-pool-bridge}"
export VCLUSTER_INGRESS_CLASS="${VCLUSTER_INGRESS_CLASS:-nginx}"
export VCLUSTER_ENABLE_INGRESS="${VCLUSTER_ENABLE_INGRESS:-1}"
export VCLUSTER_HOST_TEMPLATE="${VCLUSTER_HOST_TEMPLATE:-vcluster-[cluster].[slug].sslip.io}"

# Worker automation
export JOIN_SCRIPT_PATH="${JOIN_SCRIPT_PATH:-/root/join-worker.sh}"

# Estado / logs
export STATE_DIR="/var/opt/cluster-state"
export LOG_FILE="/var/log/cluster-install.log"
