#!/bin/bash
# shellcheck disable=SC2034

# Diretório raiz do repositório (funciona para source interativo e execução via scripts/bin/lib.sh)
export ROOT_DIR="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"

# Platform mode
export PLATFORM_MODE="${PLATFORM_MODE:-oke}"

# Inventário de nós (legado bare-metal)
export CP_IP="${CP_IP:-192.168.30.52}"
export WORKERS=("192.168.30.53" "192.168.30.54")
export REMOTE_SSH_USER="${REMOTE_SSH_USER:-utfpr}"
REMOTE_DEFAULT_BASE_DIR="/home/${REMOTE_SSH_USER}/adb-k8s"
export REMOTE_BASE_DIR="${REMOTE_BASE_DIR:-${REMOTE_DEFAULT_BASE_DIR}}"
REMOTE_DEFAULT_CONTROL_PATH="${HOME}/.ssh/adb-%C"
export REMOTE_SSH_CONTROL_PATH="${REMOTE_SSH_CONTROL_PATH:-${REMOTE_DEFAULT_CONTROL_PATH}}"
REMOTE_DEFAULT_SSH_OPTIONS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60 -o ControlPath=${REMOTE_SSH_CONTROL_PATH}"
export REMOTE_SSH_OPTIONS="${REMOTE_SSH_OPTIONS:-${REMOTE_DEFAULT_SSH_OPTIONS}}"

# Networking
export POD_CIDR="10.10.0.0/16"
export SVC_CIDR="10.96.0.0/12"

# Ingress/LB
# Deixe em branco para descoberta dinâmica quando aplicável.
export INGRESS_VIP="${INGRESS_VIP:-}"

# Hostnames (opcionais)
export RANCHER_HOST_OVERRIDE=""
export GRAFANA_HOST_OVERRIDE=""
export LONGHORN_HOST_OVERRIDE=""
export HUBBLE_HOST_OVERRIDE=""
export ARGOCD_HOST_OVERRIDE=""
export BASE_DOMAIN="${BASE_DOMAIN:-adb.internal}"
export INGRESS_HOST_TEMPLATE="${INGRESS_HOST_TEMPLATE:-%s.%s.${BASE_DOMAIN}}"

# TLS
export TLS_ENABLED="${TLS_ENABLED:-0}"
export TLS_CLUSTER_ISSUER="${TLS_CLUSTER_ISSUER:-selfsigned-cluster-issuer}"

# Observability
export PROMETHEUS_REQUEST_CPU="${PROMETHEUS_REQUEST_CPU:-100m}"
export PROMETHEUS_SCRAPE_INTERVAL="${PROMETHEUS_SCRAPE_INTERVAL:-30s}"
export PROMETHEUS_REMOTE_WRITE_RECEIVER_ENABLED="${PROMETHEUS_REMOTE_WRITE_RECEIVER_ENABLED:-1}"
export K6_PROMETHEUS_REMOTE_WRITE_ENABLED="${K6_PROMETHEUS_REMOTE_WRITE_ENABLED:-1}"
export K6_PROMETHEUS_RW_SERVER_URL="${K6_PROMETHEUS_RW_SERVER_URL:-http://kube-prometheus-stack-prometheus.monitoring.svc:9090/api/v1/write}"
export K6_PROMETHEUS_RW_TREND_STATS="${K6_PROMETHEUS_RW_TREND_STATS:-avg,min,max,p(90),p(95),p(99)}"
export K6_PROMETHEUS_RW_PUSH_INTERVAL="${K6_PROMETHEUS_RW_PUSH_INTERVAL:-5s}"
export K6_PROMETHEUS_RW_STALE_MARKERS="${K6_PROMETHEUS_RW_STALE_MARKERS:-false}"
export METRICS_SERVER_NAMESPACE="${METRICS_SERVER_NAMESPACE:-kube-system}"
export METRICS_SERVER_SERVICE_NAME="${METRICS_SERVER_SERVICE_NAME:-metrics-server}"
export METRICS_SERVER_SERVICE_PORT="${METRICS_SERVER_SERVICE_PORT:-443}"
export METRICS_SERVER_REQUEST_CPU="${METRICS_SERVER_REQUEST_CPU:-50m}"
export METRICS_SERVER_REQUEST_MEMORY="${METRICS_SERVER_REQUEST_MEMORY:-96Mi}"
export METRICS_SERVER_LIMIT_CPU="${METRICS_SERVER_LIMIT_CPU:-200m}"
export METRICS_SERVER_LIMIT_MEMORY="${METRICS_SERVER_LIMIT_MEMORY:-256Mi}"
export METRICS_SERVER_RESOLUTION="${METRICS_SERVER_RESOLUTION:-30s}"
export METRICS_SERVER_KUBELET_ADDRESS_TYPES="${METRICS_SERVER_KUBELET_ADDRESS_TYPES:-InternalIP,ExternalIP,Hostname}"
export METRICS_SERVER_KUBELET_INSECURE_TLS="${METRICS_SERVER_KUBELET_INSECURE_TLS:-1}"
export VCLUSTER_METRICS_SERVER_ENABLED="${VCLUSTER_METRICS_SERVER_ENABLED:-1}"

# Rancher
export RANCHER_REPLICAS="${RANCHER_REPLICAS:-1}"
export RANCHER_ENABLE_FLEET="${RANCHER_ENABLE_FLEET:-0}"
export RANCHER_ENABLE_TELEMETRY="${RANCHER_ENABLE_TELEMETRY:-0}"
export RANCHER_STARTUP_FAILURE_THRESHOLD="${RANCHER_STARTUP_FAILURE_THRESHOLD:-30}"
export RANCHER_HELM_CHART_OVERRIDE="${RANCHER_HELM_CHART_OVERRIDE:-}"

# Argo CD
export ARGOCD_NAMESPACE="${ARGOCD_NAMESPACE:-argocd}"
export ARGOCD_VALIDATE_CLUSTER_CONNECTIVITY="${ARGOCD_VALIDATE_CLUSTER_CONNECTIVITY:-0}"
export ADB_API_LOCAL_DIR="${ADB_API_LOCAL_DIR:-${ROOT_DIR}/../adb-api-3}"
export INTERPOLATION_LOCAL_DIR="${INTERPOLATION_LOCAL_DIR:-${ROOT_DIR}/../adb-interpolation-api}"

if [[ ! -d "${ADB_API_LOCAL_DIR}" && -d "${ROOT_DIR}/../adb-api-3" ]]; then
  export ADB_API_LOCAL_DIR="${ROOT_DIR}/../adb-api-3"
fi

if [[ ! -d "${INTERPOLATION_LOCAL_DIR}" && -d "${ROOT_DIR}/../adb-interpolation-api" ]]; then
  export INTERPOLATION_LOCAL_DIR="${ROOT_DIR}/../adb-interpolation-api"
fi

# Tenants / vCluster

# tenant configurado em `adb-api-3/k8s/tenants`
export TENANTS="${TENANTS:-abc}"
export TENANT_NAMESPACE_PREFIX="${TENANT_NAMESPACE_PREFIX:-vcluster-}"
export TENANT_TARGET_NAMESPACE="${TENANT_TARGET_NAMESPACE:-app}"
export TENANT_APP_NAMESPACE="${TENANT_APP_NAMESPACE:-${TENANT_TARGET_NAMESPACE}}"
export SHARED_VCLUSTER_NAME="${SHARED_VCLUSTER_NAME:-shared}"
export SHARED_VCLUSTER_NAMESPACE="${SHARED_VCLUSTER_NAMESPACE:-vcluster-shared}"
export ENABLE_SHARED_VCLUSTER="${ENABLE_SHARED_VCLUSTER:-1}"

# Argo CD applications (GitOps)
export ADB_API_PATH_ROOT="${ADB_API_PATH_ROOT:-k8s/tenants}"
export INTERPOLATION_PATH="${INTERPOLATION_PATH:-k8s/overlays/shared}"
export INTERPOLATION_NAMESPACE="${INTERPOLATION_NAMESPACE:-processing}"

# vCluster resource profiles (override apenas se necessário)
export PRIVATE_API_REQUEST_CPU="${PRIVATE_API_REQUEST_CPU:-120m}"
export PRIVATE_API_REQUEST_MEMORY="${PRIVATE_API_REQUEST_MEMORY:-192Mi}"
export PRIVATE_API_LIMIT_CPU="${PRIVATE_API_LIMIT_CPU:-600m}"
export PRIVATE_API_LIMIT_MEMORY="${PRIVATE_API_LIMIT_MEMORY:-512Mi}"
export PRIVATE_CONTROLLER_MANAGER_REQUEST_CPU="${PRIVATE_CONTROLLER_MANAGER_REQUEST_CPU:-90m}"
export PRIVATE_CONTROLLER_MANAGER_REQUEST_MEMORY="${PRIVATE_CONTROLLER_MANAGER_REQUEST_MEMORY:-160Mi}"
export PRIVATE_CONTROLLER_MANAGER_LIMIT_CPU="${PRIVATE_CONTROLLER_MANAGER_LIMIT_CPU:-400m}"
export PRIVATE_CONTROLLER_MANAGER_LIMIT_MEMORY="${PRIVATE_CONTROLLER_MANAGER_LIMIT_MEMORY:-384Mi}"
export PRIVATE_SCHEDULER_REQUEST_CPU="${PRIVATE_SCHEDULER_REQUEST_CPU:-60m}"
export PRIVATE_SCHEDULER_REQUEST_MEMORY="${PRIVATE_SCHEDULER_REQUEST_MEMORY:-96Mi}"
export PRIVATE_SCHEDULER_LIMIT_CPU="${PRIVATE_SCHEDULER_LIMIT_CPU:-300m}"
export PRIVATE_SCHEDULER_LIMIT_MEMORY="${PRIVATE_SCHEDULER_LIMIT_MEMORY:-256Mi}"
export PRIVATE_SYNCER_REQUEST_CPU="${PRIVATE_SYNCER_REQUEST_CPU:-100m}"
export PRIVATE_SYNCER_REQUEST_MEMORY="${PRIVATE_SYNCER_REQUEST_MEMORY:-192Mi}"
export PRIVATE_SYNCER_LIMIT_CPU="${PRIVATE_SYNCER_LIMIT_CPU:-500m}"
export PRIVATE_SYNCER_LIMIT_MEMORY="${PRIVATE_SYNCER_LIMIT_MEMORY:-512Mi}"
export PRIVATE_CONTROL_PLANE_REPLICAS="${PRIVATE_CONTROL_PLANE_REPLICAS:-1}"
export PRIVATE_CONTROL_PLANE_REQUEST_CPU="${PRIVATE_CONTROL_PLANE_REQUEST_CPU:-250m}"
export PRIVATE_CONTROL_PLANE_REQUEST_MEMORY="${PRIVATE_CONTROL_PLANE_REQUEST_MEMORY:-448Mi}"
export PRIVATE_CONTROL_PLANE_LIMIT_CPU="${PRIVATE_CONTROL_PLANE_LIMIT_CPU:-1300m}"
export PRIVATE_CONTROL_PLANE_LIMIT_MEMORY="${PRIVATE_CONTROL_PLANE_LIMIT_MEMORY:-1152Mi}"
export PRIVATE_CONTROL_PLANE_K8S_VERSION="${PRIVATE_CONTROL_PLANE_K8S_VERSION:-}"

export SHARED_API_REQUEST_CPU="${SHARED_API_REQUEST_CPU:-150m}"
export SHARED_API_REQUEST_MEMORY="${SHARED_API_REQUEST_MEMORY:-224Mi}"
export SHARED_API_LIMIT_CPU="${SHARED_API_LIMIT_CPU:-700m}"
export SHARED_API_LIMIT_MEMORY="${SHARED_API_LIMIT_MEMORY:-640Mi}"
export SHARED_CONTROLLER_MANAGER_REQUEST_CPU="${SHARED_CONTROLLER_MANAGER_REQUEST_CPU:-100m}"
export SHARED_CONTROLLER_MANAGER_REQUEST_MEMORY="${SHARED_CONTROLLER_MANAGER_REQUEST_MEMORY:-192Mi}"
export SHARED_CONTROLLER_MANAGER_LIMIT_CPU="${SHARED_CONTROLLER_MANAGER_LIMIT_CPU:-450m}"
export SHARED_CONTROLLER_MANAGER_LIMIT_MEMORY="${SHARED_CONTROLLER_MANAGER_LIMIT_MEMORY:-448Mi}"
export SHARED_SCHEDULER_REQUEST_CPU="${SHARED_SCHEDULER_REQUEST_CPU:-70m}"
export SHARED_SCHEDULER_REQUEST_MEMORY="${SHARED_SCHEDULER_REQUEST_MEMORY:-128Mi}"
export SHARED_SCHEDULER_LIMIT_CPU="${SHARED_SCHEDULER_LIMIT_CPU:-320m}"
export SHARED_SCHEDULER_LIMIT_MEMORY="${SHARED_SCHEDULER_LIMIT_MEMORY:-320Mi}"
export SHARED_SYNCER_REQUEST_CPU="${SHARED_SYNCER_REQUEST_CPU:-120m}"
export SHARED_SYNCER_REQUEST_MEMORY="${SHARED_SYNCER_REQUEST_MEMORY:-192Mi}"
export SHARED_SYNCER_LIMIT_CPU="${SHARED_SYNCER_LIMIT_CPU:-520m}"
export SHARED_SYNCER_LIMIT_MEMORY="${SHARED_SYNCER_LIMIT_MEMORY:-512Mi}"
export SHARED_CONTROL_PLANE_REPLICAS="${SHARED_CONTROL_PLANE_REPLICAS:-1}"
export SHARED_CONTROL_PLANE_REQUEST_CPU="${SHARED_CONTROL_PLANE_REQUEST_CPU:-300m}"
export SHARED_CONTROL_PLANE_REQUEST_MEMORY="${SHARED_CONTROL_PLANE_REQUEST_MEMORY:-512Mi}"
export SHARED_CONTROL_PLANE_LIMIT_CPU="${SHARED_CONTROL_PLANE_LIMIT_CPU:-1470m}"
export SHARED_CONTROL_PLANE_LIMIT_MEMORY="${SHARED_CONTROL_PLANE_LIMIT_MEMORY:-1408Mi}"
export SHARED_CONTROL_PLANE_K8S_VERSION="${SHARED_CONTROL_PLANE_K8S_VERSION:-}"

export VC_TENANT_MANIFEST_ROOT="${VC_TENANT_MANIFEST_ROOT:-${ROOT_DIR}/../adb-api-3/k8s/tenants}"
export VC_INTERPOLATION_OVERLAY_DIR="${VC_INTERPOLATION_OVERLAY_DIR:-${ROOT_DIR}/../adb-interpolation-api/k8s/overlays/shared}"
if [[ ! -d "${VC_TENANT_MANIFEST_ROOT}" && -d "${ROOT_DIR}/../adb-api-3/k8s/tenants" ]]; then
  export VC_TENANT_MANIFEST_ROOT="${ROOT_DIR}/../adb-api-3/k8s/tenants"
fi
if [[ ! -d "${VC_INTERPOLATION_OVERLAY_DIR}" && -d "${ROOT_DIR}/../adb-interpolation-api/k8s/overlays/shared" ]]; then
  export VC_INTERPOLATION_OVERLAY_DIR="${ROOT_DIR}/../adb-interpolation-api/k8s/overlays/shared"
fi
export OKE_LB_TYPE_DEFAULT="${OKE_LB_TYPE_DEFAULT:-nlb}"
export OKE_LB_INTERNAL_DEFAULT="${OKE_LB_INTERNAL_DEFAULT:-true}"
export OKE_LB_SECURITY_RULE_MODE="${OKE_LB_SECURITY_RULE_MODE:-NSG}"
export VCLUSTER_SERVICE_TYPE="${VCLUSTER_SERVICE_TYPE:-LoadBalancer}"
export VCLUSTER_INGRESS_CLASS="${VCLUSTER_INGRESS_CLASS:-native-oci}"
export VCLUSTER_ENABLE_INGRESS="${VCLUSTER_ENABLE_INGRESS:-0}"
export VCLUSTER_HOST_TEMPLATE="${VCLUSTER_HOST_TEMPLATE:-vcluster-[cluster].[slug].${BASE_DOMAIN}}"
export VCLUSTER_LOAD_BALANCER_TYPE="${VCLUSTER_LOAD_BALANCER_TYPE:-${OKE_LB_TYPE_DEFAULT}}"
export VCLUSTER_LOAD_BALANCER_INTERNAL="${VCLUSTER_LOAD_BALANCER_INTERNAL:-${OKE_LB_INTERNAL_DEFAULT}}"
export VCLUSTER_LB_SECURITY_RULE_MODE="${VCLUSTER_LB_SECURITY_RULE_MODE:-${OKE_LB_SECURITY_RULE_MODE}}"
export ARGOCD_LB_TYPE="${ARGOCD_LB_TYPE:-${OKE_LB_TYPE_DEFAULT}}"
export ARGOCD_LB_INTERNAL="${ARGOCD_LB_INTERNAL:-${OKE_LB_INTERNAL_DEFAULT}}"
export ARGOCD_LB_SECURITY_RULE_MODE="${ARGOCD_LB_SECURITY_RULE_MODE:-${OKE_LB_SECURITY_RULE_MODE}}"
export GRAFANA_LB_TYPE="${GRAFANA_LB_TYPE:-${OKE_LB_TYPE_DEFAULT}}"
export GRAFANA_LB_INTERNAL="${GRAFANA_LB_INTERNAL:-${OKE_LB_INTERNAL_DEFAULT}}"
export GRAFANA_LB_SECURITY_RULE_MODE="${GRAFANA_LB_SECURITY_RULE_MODE:-${OKE_LB_SECURITY_RULE_MODE}}"
export LONGHORN_DEFAULT_REPLICA_COUNT="${LONGHORN_DEFAULT_REPLICA_COUNT:-2}"
export LONGHORN_STORAGECLASS_NAME="${LONGHORN_STORAGECLASS_NAME:-longhorn-2}"
export LONGHORN_LB_TYPE="${LONGHORN_LB_TYPE:-${OKE_LB_TYPE_DEFAULT}}"
export LONGHORN_LB_INTERNAL="${LONGHORN_LB_INTERNAL:-${OKE_LB_INTERNAL_DEFAULT}}"
export LONGHORN_LB_SECURITY_RULE_MODE="${LONGHORN_LB_SECURITY_RULE_MODE:-${OKE_LB_SECURITY_RULE_MODE}}"
export SHARED_INTERPOLATION_HOST="${SHARED_INTERPOLATION_HOST:-adb-interpolation-api.processing.svc.cluster.local}"
export VCLUSTER_COREDNS_IMAGE="${VCLUSTER_COREDNS_IMAGE:-docker.io/coredns/coredns:1.14.1}"
export ENABLE_HUBBLE_INGRESS="${ENABLE_HUBBLE_INGRESS:-0}"

# Worker automation
export JOIN_SCRIPT_PATH="${JOIN_SCRIPT_PATH:-/root/join-worker.sh}"

# Estado / logs
__ADB_STATE_BASE="${ROOT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
export STATE_DIR="${STATE_DIR:-${__ADB_STATE_BASE}/.state/cluster-state}"
export LOG_FILE="${LOG_FILE:-${__ADB_STATE_BASE}/.state/cluster-install.log}"
unset __ADB_STATE_BASE

if [[ $- == *i* ]]; then
  __ADB_ENV_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
  if [[ -z "${ADB_PROMPT_CTX_DISABLED:-}" && -f "${__ADB_ENV_DIR}/scripts/vcluster/prompt.sh" ]]; then
    # shellcheck disable=SC1091
    source "${__ADB_ENV_DIR}/scripts/vcluster/prompt.sh"
  fi
  unset __ADB_ENV_DIR
fi
